version: '3'
services:
  asuna-kafka-producer:
    image: asuna-data-mongo-reactive
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8201:8201"
    restart: always
    environment:
      - SPRING_BOOTSTRAP-SERVERS=broker:9092
    volumes:
      - /data/asuna-data-mongo-reactive