version: '3'
services:
  asuna-discovery-server:
    image: asuna-discovery-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    environment:
      - SERVER_PORT= 8001
    volumes:
      - /data/asuna-discovery-server