springdoc:
  swagger-ui:
    operationsSorter: alpha
    path: /swagger-ui.html
  pathsToMatch: /**
server:
  port: 9102
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
spring:
  application:
    name: asuna-data-jpa
  profiles:
    active: native
  datasource:
    url: jdbc:h2:file:/data/asuna
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      show-sql: 'true'
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: 'true'
      path: /h2-ui
